<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Articles.Application\Articles.Application.csproj" />
      <ProjectReference Include="..\Articles.Domain\Articles.Domain.csproj" />
    </ItemGroup>
    
</Project>
