// <auto-generated />
using System;
using Articles.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Articles.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805135515_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.ArticleDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_articles_section_id");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.SectionDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.SectionTagDbModel", b =>
                {
                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<int>("SortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sort_number");

                    b.HasKey("SectionId", "TagId")
                        .HasName("pk_section_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_section_tags_tag_id");

                    b.ToTable("section_tags", (string)null);
                });

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.TagDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tags_name")
                        .HasAnnotation("Npgsql:TsVectorConfig", "russian");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_normalized_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.ArticleDbModel", b =>
                {
                    b.HasOne("Articles.Infrastructure.Data.Models.SectionDbModel", "Section")
                        .WithMany("Articles")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_articles_sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.SectionTagDbModel", b =>
                {
                    b.HasOne("Articles.Infrastructure.Data.Models.SectionDbModel", "Section")
                        .WithMany("SectionTags")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_tags_sections_section_id");

                    b.HasOne("Articles.Infrastructure.Data.Models.TagDbModel", "Tag")
                        .WithMany("SectionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_tags_tags_tag_id");

                    b.Navigation("Section");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.SectionDbModel", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("SectionTags");
                });

            modelBuilder.Entity("Articles.Infrastructure.Data.Models.TagDbModel", b =>
                {
                    b.Navigation("SectionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
